
library(dplyr)
library(srvyr) 
library(readr)
library(tidyr)
library(readxl)

# Pasta de Trabalho
setwd("C:\\Users\\pc\\Downloads\\Leitos COVID")

# datasets
sesab <- read_excel("Banco_Estadual_COVID-19_20-07-2020.xlsx", sheet = 1)
codigos_mun <- read.csv2("codigos_mun_v2.csv") #%>% select(Nome_Município, Codigo_mun)
nrs_pop <- read.csv2("populacao_municipios.csv") %>% select(CD_GEOCMU, NM_MUNICIP2, NRS, NM_RS,
                                                            LONG, LAT, POP_MUN)

# Ajustando nomes dos municipios e UF's
Sesab_v2 <- sesab %>% mutate(municipio_residencia = case_when(
    `MUNICIPIO DE RESIDENCIA` == "ABAIRA" ~ "Abaíra",
    `MUNICIPIO DE RESIDENCIA` == "ABARE" ~ "Abaré",
    `MUNICIPIO DE RESIDENCIA` == "ACAJUTIBA" ~ "Acajutiba",
    `MUNICIPIO DE RESIDENCIA` == "ADUSTINA" ~ "Adustina",
    `MUNICIPIO DE RESIDENCIA` == "AGUA FRIA" ~ "Água Fria",
    `MUNICIPIO DE RESIDENCIA` == "AIQUARA" ~ "Aiquara",
    `MUNICIPIO DE RESIDENCIA` == "ALAGOINHAS" ~ "Alagoinhas",
    `MUNICIPIO DE RESIDENCIA` == "ALCOBACA" ~ "Alcobaça",
    `MUNICIPIO DE RESIDENCIA` == "ALMADINA" ~ "Almadina",
    `MUNICIPIO DE RESIDENCIA` == "AMARGOSA" ~ "Amargosa",
    `MUNICIPIO DE RESIDENCIA` == "AMELIA RODRIGUES" ~ "Amélia Rodrigues",
    `MUNICIPIO DE RESIDENCIA` == "AMERICA DOURADA" ~ "América Dourada",
    `MUNICIPIO DE RESIDENCIA` == "ANAGE" ~ "Anagé",
    `MUNICIPIO DE RESIDENCIA` == "ANDARAI" ~ "Andaraí",
    `MUNICIPIO DE RESIDENCIA` == "ANDORINHA" ~ "Andorinha",
    `MUNICIPIO DE RESIDENCIA` == "ANGICAL" ~ "Angical",
    `MUNICIPIO DE RESIDENCIA` == "ANGUERA" ~ "Anguera",
    `MUNICIPIO DE RESIDENCIA` == "ANTAS" ~ "Antas",
    `MUNICIPIO DE RESIDENCIA` == "ANTONIO CARDOSO" ~ "Antônio Cardoso",
    `MUNICIPIO DE RESIDENCIA` == "ANTONIO GONCALVES" ~ "Antônio Gonçalves",
    `MUNICIPIO DE RESIDENCIA` == "APORA" ~ "Aporá",
    `MUNICIPIO DE RESIDENCIA` == "APUAREMA" ~ "Apuarema",
    `MUNICIPIO DE RESIDENCIA` == "ARACAS" ~ "Araçás",
    `MUNICIPIO DE RESIDENCIA` == "ARACATU" ~ "Aracatu",
    `MUNICIPIO DE RESIDENCIA` == "ARACI" ~ "Araci",
    `MUNICIPIO DE RESIDENCIA` == "ARAMARI" ~ "Aramari",
    `MUNICIPIO DE RESIDENCIA` == "ARATACA" ~ "Arataca",
    `MUNICIPIO DE RESIDENCIA` == "ARATUIPE" ~ "Aratuípe",
    `MUNICIPIO DE RESIDENCIA` == "AURELINO LEAL" ~ "Aurelino Leal",
    `MUNICIPIO DE RESIDENCIA` == "BAIANOPOLIS" ~ "Baianópolis",
    `MUNICIPIO DE RESIDENCIA` == "BAIXA GRANDE" ~ "Baixa Grande",
    `MUNICIPIO DE RESIDENCIA` == "BANZAE" ~ "Banzaê",
    `MUNICIPIO DE RESIDENCIA` == "BARRA" ~ "Barra",
    `MUNICIPIO DE RESIDENCIA` == "BARRA DA ESTIVA" ~ "Barra da Estiva",
    `MUNICIPIO DE RESIDENCIA` == "BARRA DO CHOCA" ~ "Barra do Choça",
    `MUNICIPIO DE RESIDENCIA` == "BARRA DO MENDES" ~ "Barra do Mendes",
    `MUNICIPIO DE RESIDENCIA` == "BARRA DO ROCHA" ~ "Barra do Rocha",
    `MUNICIPIO DE RESIDENCIA` == "BARREIRAS" ~ "Barreiras",
    `MUNICIPIO DE RESIDENCIA` == "BARRO ALTO" ~ "Barro Alto",
    `MUNICIPIO DE RESIDENCIA` == "BARRO PRETO" ~ "Barro Preto",
    `MUNICIPIO DE RESIDENCIA` == "BARROCAS" ~ "Barrocas",
    `MUNICIPIO DE RESIDENCIA` == "BELMONTE" ~ "Belmonte",
    `MUNICIPIO DE RESIDENCIA` == "BELO CAMPO" ~ "Belo Campo",
    `MUNICIPIO DE RESIDENCIA` == "BIRITINGA" ~ "Biritinga",
    `MUNICIPIO DE RESIDENCIA` == "BOA NOVA" ~ "Boa Nova",
    `MUNICIPIO DE RESIDENCIA` == "BOA VISTA DO TUPIM" ~ "Boa Vista do Tupim",
    `MUNICIPIO DE RESIDENCIA` == "BOM JESUS DA LAPA" ~ "Bom Jesus da Lapa",
    `MUNICIPIO DE RESIDENCIA` == "BOM JESUS DA SERRA" ~ "Bom Jesus da Serra",
    `MUNICIPIO DE RESIDENCIA` == "BONINAL" ~ "Boninal",
    `MUNICIPIO DE RESIDENCIA` == "BONITO" ~ "Bonito",
    `MUNICIPIO DE RESIDENCIA` == "BOQUIRA" ~ "Boquira",
    `MUNICIPIO DE RESIDENCIA` == "BOTUPORA" ~ "Botuporã",
    `MUNICIPIO DE RESIDENCIA` == "BREJ??ES" ~ "Brejões",
    `MUNICIPIO DE RESIDENCIA` == "BREJOES" ~ "Brejões",
    `MUNICIPIO DE RESIDENCIA` == "BREJOLANDIA" ~ "Brejolândia",
    `MUNICIPIO DE RESIDENCIA` == "BROTAS DE MACAUBAS" ~ "Brotas de Macaúbas",
    `MUNICIPIO DE RESIDENCIA` == "BRUMADO" ~ "Brumado",
    `MUNICIPIO DE RESIDENCIA` == "BUERAREMA" ~ "Buerarema",
    `MUNICIPIO DE RESIDENCIA` == "BURITIRAMA" ~ "Buritirama", 
    `MUNICIPIO DE RESIDENCIA` == "CAATIBA" ~ "Caatiba",
    `MUNICIPIO DE RESIDENCIA` == "CABACEIRAS DO PARAGUACU" ~ "Cabaceiras do Paraguaçu",
    `MUNICIPIO DE RESIDENCIA` == "CACHOEIRA" ~ "Cachoeira",
    `MUNICIPIO DE RESIDENCIA` == "CACULE" ~ "Caculé",
    `MUNICIPIO DE RESIDENCIA` == "CAEM" ~ "Caém",
    `MUNICIPIO DE RESIDENCIA` == "CAETANOS" ~ "Caetanos",
    `MUNICIPIO DE RESIDENCIA` == "CAETITE" ~ "Caetité",
    `MUNICIPIO DE RESIDENCIA` == "CAFARNAUM" ~ "Cafarnaum",
    `MUNICIPIO DE RESIDENCIA` == "CAIRU" ~ "Cairu",
    `MUNICIPIO DE RESIDENCIA` == "CALDEIRAO GRANDE" ~ "Caldeirão Grande",
    `MUNICIPIO DE RESIDENCIA` == "CAMACAN" ~ "Camacan",
    `MUNICIPIO DE RESIDENCIA` == "CAMACARI" ~ "Camaçari",
    `MUNICIPIO DE RESIDENCIA` == "CAMAMU" ~ "Camamu",
    `MUNICIPIO DE RESIDENCIA` == "CAMPO ALEGRE DE LOURDES" ~ "Campo Alegre de Lourdes",
    `MUNICIPIO DE RESIDENCIA` == "CAMPO FORMOSO" ~ "Campo Formoso",
    `MUNICIPIO DE RESIDENCIA` == "CANAPOLIS" ~ "Canápolis",
    `MUNICIPIO DE RESIDENCIA` == "CANARANA" ~ "Canarana",
    `MUNICIPIO DE RESIDENCIA` == "CANAVIEIRAS" ~ "Canavieiras",
    `MUNICIPIO DE RESIDENCIA` == "CANDEAL" ~ "Candeal",
    `MUNICIPIO DE RESIDENCIA` == "CANDEIAS" ~ "Candeias",
    `MUNICIPIO DE RESIDENCIA` == "CANDIBA" ~ "Candiba",
    `MUNICIPIO DE RESIDENCIA` == "CANDIDO SALES" ~ "Cândido Sales",
    `MUNICIPIO DE RESIDENCIA` == "CANSANCAO" ~ "Cansanção",
    `MUNICIPIO DE RESIDENCIA` == "CANUDOS" ~ "Canudos",
    `MUNICIPIO DE RESIDENCIA` == "CAPELA DO ALTO ALEGRE" ~ "Capela do Alto Alegre",
    `MUNICIPIO DE RESIDENCIA` == "CAPIM GROSSO" ~ "Capim Grosso",
    `MUNICIPIO DE RESIDENCIA` == "CARAIBAS" ~ "Caraíbas",
    `MUNICIPIO DE RESIDENCIA` == "CARAVELAS" ~ "Caravelas",
    `MUNICIPIO DE RESIDENCIA` == "CARDEAL DA SILVA" ~ "Cardeal da Silva",
    `MUNICIPIO DE RESIDENCIA` == "CARINHANHA" ~ "Carinhanha",
    `MUNICIPIO DE RESIDENCIA` == "CASA NOVA" ~ "Casa Nova",
    `MUNICIPIO DE RESIDENCIA` == "CASTRO ALVES" ~ "Castro Alves",
    `MUNICIPIO DE RESIDENCIA` == "CATOLANDIA" ~ "Catolândia",
    `MUNICIPIO DE RESIDENCIA` == "CATU" ~ "Catu",
    `MUNICIPIO DE RESIDENCIA` == "CATURAMA" ~ "Caturama",
    `MUNICIPIO DE RESIDENCIA` == "CENTRAL" ~ "Central",
    `MUNICIPIO DE RESIDENCIA` == "CHORROCHO" ~ "Chorrochó",
    `MUNICIPIO DE RESIDENCIA` == "CICERO DANTAS" ~ "Cícero Dantas",
    `MUNICIPIO DE RESIDENCIA` == "CIPO" ~ "Cipó",
    `MUNICIPIO DE RESIDENCIA` == "COARACI" ~ "Coaraci",
    `MUNICIPIO DE RESIDENCIA` == "COCOS" ~ "Cocos",
    `MUNICIPIO DE RESIDENCIA` == "CONCEICAO DA FEIRA" ~ "Conceição da Feira",
    `MUNICIPIO DE RESIDENCIA` == "CONCEICAO DO ALMEIDA" ~ "Conceição do Almeida",
    `MUNICIPIO DE RESIDENCIA` == "CONCEICAO DO COITE" ~ "Conceição do Coité",
    `MUNICIPIO DE RESIDENCIA` == "CONCEICAO DO JACUIPE" ~ "Conceição do Jacuípe",
    `MUNICIPIO DE RESIDENCIA` == "CONDE" ~ "Conde",
    `MUNICIPIO DE RESIDENCIA` == "CONDEUBA" ~ "Condeúba",
    `MUNICIPIO DE RESIDENCIA` == "CONTENDAS DO SINCORA" ~ "Contendas do Sincorá",
    `MUNICIPIO DE RESIDENCIA` == "CORACAO DE MARIA" ~ "Coração de Maria",
    `MUNICIPIO DE RESIDENCIA` == "CORDEIROS" ~ "Cordeiros",
    `MUNICIPIO DE RESIDENCIA` == "CORIBE" ~ "Coribe",
    `MUNICIPIO DE RESIDENCIA` == "CORONEL JOAO SA" ~ "Coronel João Sá",
    `MUNICIPIO DE RESIDENCIA` == "CORRENTINA" ~ "Correntina",
    `MUNICIPIO DE RESIDENCIA` == "COTEGIPE" ~ "Cotegipe",
    `MUNICIPIO DE RESIDENCIA` == "CRAVOLANDIA" ~ "Cravolândia",
    `MUNICIPIO DE RESIDENCIA` == "CRISOPOLIS" ~ "Crisópolis",
    `MUNICIPIO DE RESIDENCIA` == "CRISTOPOLIS" ~ "Cristópolis",
    `MUNICIPIO DE RESIDENCIA` == "CRUZ DAS ALMAS" ~ "Cruz das Almas",
    `MUNICIPIO DE RESIDENCIA` == "CURACA" ~ "Curaçá",
    `MUNICIPIO DE RESIDENCIA` == "DARIO MEIRA" ~ "Dário Meira",
    `MUNICIPIO DE RESIDENCIA` == "DIAS D'AVILA" ~ "Dias d'Ávila",
    `MUNICIPIO DE RESIDENCIA` == "DIAS D''AVILA" ~ "Dias d'Ávila",
    `MUNICIPIO DE RESIDENCIA` == "DOM BASILIO" ~ "Dom Basílio",
    `MUNICIPIO DE RESIDENCIA` == "DOM MACEDO COSTA" ~ "Dom Macedo Costa",
    `MUNICIPIO DE RESIDENCIA` == "ELISIO MEDRADO" ~ "Elísio Medrado",
    `MUNICIPIO DE RESIDENCIA` == "ENCRUZILHADA" ~ "Encruzilhada",
    `MUNICIPIO DE RESIDENCIA` == "ENTRE RIOS" ~ "Entre Rios",
    `MUNICIPIO DE RESIDENCIA` == "ERICO CARDOSO" ~ "Érico Cardoso",
    `MUNICIPIO DE RESIDENCIA` == "ESPLANADA" ~ "Esplanada",
    `MUNICIPIO DE RESIDENCIA` == "EUCLIDES DA CUNHA" ~ "Euclides da Cunha",
    `MUNICIPIO DE RESIDENCIA` == "EUNAPOLIS" ~ "Eunápolis",
    `MUNICIPIO DE RESIDENCIA` == "FATIMA" ~ "Fátima",
    `MUNICIPIO DE RESIDENCIA` == "FEIRA DA MATA" ~ "Feira da Mata",
    `MUNICIPIO DE RESIDENCIA` == "FEIRA DE SANTANA" ~ "Feira de Santana", 
    `MUNICIPIO DE RESIDENCIA` == "FILADELFIA" ~ "Filadélfia",
    `MUNICIPIO DE RESIDENCIA` == "FIRMINO ALVES" ~ "Firmino Alves",
    `MUNICIPIO DE RESIDENCIA` == "FLORESTA AZUL" ~ "Floresta Azul",
    `MUNICIPIO DE RESIDENCIA` == "FORMOSA DO RIO PRETO" ~ "Formosa do Rio Preto",
    `MUNICIPIO DE RESIDENCIA` == "GANDU" ~ "Gandu",
    `MUNICIPIO DE RESIDENCIA` == "GAVIAO" ~ "Gavião",
    `MUNICIPIO DE RESIDENCIA` == "GENTIO DO OURO" ~ "Gentio do Ouro",
    `MUNICIPIO DE RESIDENCIA` == "GLORIA" ~ "Glória",
    `MUNICIPIO DE RESIDENCIA` == "GONGOGI" ~ "Gongogi",
    `MUNICIPIO DE RESIDENCIA` == "GOVERNADOR MANGABEIRA" ~ "Governador Mangabeira",
    `MUNICIPIO DE RESIDENCIA` == "GUAJERU" ~ "Guajeru",
    `MUNICIPIO DE RESIDENCIA` == "GUANAMBI" ~ "Guanambi",
    `MUNICIPIO DE RESIDENCIA` == "GUARATINGA" ~ "Guaratinga",
    `MUNICIPIO DE RESIDENCIA` == "HELIOPOLIS" ~ "Heliópolis",
    `MUNICIPIO DE RESIDENCIA` == "IACU" ~ "Iaçu",
    `MUNICIPIO DE RESIDENCIA` == "IBIASSUCE" ~ "Ibiassucê",
    `MUNICIPIO DE RESIDENCIA` == "IBICARAI" ~ "Ibicaraí",
    `MUNICIPIO DE RESIDENCIA` == "IBICOARA" ~ "Ibicoara",
    `MUNICIPIO DE RESIDENCIA` == "IBICUI" ~ "Ibicuí",
    `MUNICIPIO DE RESIDENCIA` == "IBIPEBA" ~ "Ibipeba",
    `MUNICIPIO DE RESIDENCIA` == "IBIPITANGA" ~ "Ibipitanga",
    `MUNICIPIO DE RESIDENCIA` == "IBIQUERA" ~ "Ibiquera",
    `MUNICIPIO DE RESIDENCIA` == "IBIRAPITANGA" ~ "Ibirapitanga",
    `MUNICIPIO DE RESIDENCIA` == "IBIRAPUA" ~ "Ibirapoã",
    `MUNICIPIO DE RESIDENCIA` == "IBIRATAIA" ~ "Ibirataia",
    `MUNICIPIO DE RESIDENCIA` == "IBITIARA" ~ "Ibitiara",
    `MUNICIPIO DE RESIDENCIA` == "IBITITA" ~ "Ibititá",
    `MUNICIPIO DE RESIDENCIA` == "IBOTIRAMA" ~ "Ibotirama",
    `MUNICIPIO DE RESIDENCIA` == "ICHU" ~ "Ichu",
    `MUNICIPIO DE RESIDENCIA` == "IGAPORA" ~ "Igaporã",
    `MUNICIPIO DE RESIDENCIA` == "IGRAPIUNA" ~ "Igrapiúna",
    `MUNICIPIO DE RESIDENCIA` == "IGUAI" ~ "Iguaí",
    `MUNICIPIO DE RESIDENCIA` == "ILHEUS" ~ "Ilhéus",
    `MUNICIPIO DE RESIDENCIA` == "INHAMBUPE" ~ "Inhambupe",
    `MUNICIPIO DE RESIDENCIA` == "IPECAETA" ~ "Ipecaetá",
    `MUNICIPIO DE RESIDENCIA` == "IPIAU" ~ "Ipiaú",
    `MUNICIPIO DE RESIDENCIA` == "IPIRA" ~ "Ipirá",
    `MUNICIPIO DE RESIDENCIA` == "IPUPIARA" ~ "Ipupiara",
    `MUNICIPIO DE RESIDENCIA` == "IRAJUBA" ~ "Irajuba",
    `MUNICIPIO DE RESIDENCIA` == "IRAMAIA" ~ "Iramaia",
    `MUNICIPIO DE RESIDENCIA` == "IRAQUARA" ~ "Iraquara",
    `MUNICIPIO DE RESIDENCIA` == "IRARA" ~ "Irará",
    `MUNICIPIO DE RESIDENCIA` == "IRECE" ~ "Irecê",
    `MUNICIPIO DE RESIDENCIA` == "ITABELA" ~ "Itabela",
    `MUNICIPIO DE RESIDENCIA` == "ITABERABA" ~ "Itaberaba",
    `MUNICIPIO DE RESIDENCIA` == "ITABUNA" ~ "Itabuna",
    `MUNICIPIO DE RESIDENCIA` == "ITACARE" ~ "Itacaré",
    `MUNICIPIO DE RESIDENCIA` == "ITAETE" ~ "Itaeté",
    `MUNICIPIO DE RESIDENCIA` == "ITAGI" ~ "Itagi",
    `MUNICIPIO DE RESIDENCIA` == "ITAGIBA" ~ "Itagibá",
    `MUNICIPIO DE RESIDENCIA` == "ITAGIMIRIM" ~ "Itagimirim",
    `MUNICIPIO DE RESIDENCIA` == "ITAGUACU DA BAHIA" ~ "Itaguaçu da Bahia",
    `MUNICIPIO DE RESIDENCIA` == "ITAJU DO COLONIA" ~ "Itaju do Colônia",
    `MUNICIPIO DE RESIDENCIA` == "ITAJUIPE" ~ "Itajuípe",
    `MUNICIPIO DE RESIDENCIA` == "ITAMARAJU" ~ "Itamaraju",
    `MUNICIPIO DE RESIDENCIA` == "ITAMARI" ~ "Itamari",
    `MUNICIPIO DE RESIDENCIA` == "ITAMBE" ~ "Itambé",
    `MUNICIPIO DE RESIDENCIA` == "ITANAGRA" ~ "Itanagra",
    `MUNICIPIO DE RESIDENCIA` == "ITANHEM" ~ "Itanhém",
    `MUNICIPIO DE RESIDENCIA` == "ITAPARICA" ~ "Itaparica",
    `MUNICIPIO DE RESIDENCIA` == "ITAPE" ~ "Itapé",
    `MUNICIPIO DE RESIDENCIA` == "ITAPEBI" ~ "Itapebi",
    `MUNICIPIO DE RESIDENCIA` == "ITAPETINGA" ~ "Itapetinga",
    `MUNICIPIO DE RESIDENCIA` == "ITAPICURU" ~ "Itapicuru",
    `MUNICIPIO DE RESIDENCIA` == "ITAPITANGA" ~ "Itapitanga",
    `MUNICIPIO DE RESIDENCIA` == "ITAQUARA" ~ "Itaquara",
    `MUNICIPIO DE RESIDENCIA` == "ITARANTIM" ~ "Itarantim",
    `MUNICIPIO DE RESIDENCIA` == "ITATIM" ~ "Itatim",
    `MUNICIPIO DE RESIDENCIA` == "ITIRUCU" ~ "Itiruçu",
    `MUNICIPIO DE RESIDENCIA` == "ITIUBA" ~ "Itiúba",
    `MUNICIPIO DE RESIDENCIA` == "ITORORO" ~ "Itororó",
    `MUNICIPIO DE RESIDENCIA` == "ITUACU" ~ "Ituaçu",
    `MUNICIPIO DE RESIDENCIA` == "ITUBERA" ~ "Ituberá",
    `MUNICIPIO DE RESIDENCIA` == "IUIU" ~ "Iuiu",
    `MUNICIPIO DE RESIDENCIA` == "JABORANDI" ~ "Jaborandi",
    `MUNICIPIO DE RESIDENCIA` == "JACARACI" ~ "Jacaraci",
    `MUNICIPIO DE RESIDENCIA` == "JACOBINA" ~ "Jacobina",
    `MUNICIPIO DE RESIDENCIA` == "JAGUAQUARA" ~ "Jaguaquara",
    `MUNICIPIO DE RESIDENCIA` == "JAGUARARI" ~ "Jaguarari",
    `MUNICIPIO DE RESIDENCIA` == "JAGUARIPE" ~ "Jaguaripe",
    `MUNICIPIO DE RESIDENCIA` == "JANDAIRA" ~ "Jandaíra",
    `MUNICIPIO DE RESIDENCIA` == "JEQUIE" ~ "Jequié",
    `MUNICIPIO DE RESIDENCIA` == "JEREMOABO" ~ "Jeremoabo",
    `MUNICIPIO DE RESIDENCIA` == "JIQUIRICA" ~ "Jiquiriçá",
    `MUNICIPIO DE RESIDENCIA` == "JITAUNA" ~ "Jitaúna",
    `MUNICIPIO DE RESIDENCIA` == "JOAO DOURADO" ~ "João Dourado",
    `MUNICIPIO DE RESIDENCIA` == "JUAZEIRO" ~ "Juazeiro",
    `MUNICIPIO DE RESIDENCIA` == "JUCURUCU" ~ "Jucuruçu",
    `MUNICIPIO DE RESIDENCIA` == "JUSSARA" ~ "Jussara",
    `MUNICIPIO DE RESIDENCIA` == "JUSSARI" ~ "Jussari",
    `MUNICIPIO DE RESIDENCIA` == "JUSSIAPE" ~ "Jussiape",
    `MUNICIPIO DE RESIDENCIA` == "LAFAIETE COUTINHO" ~ "Lafayette Coutinho",
    `MUNICIPIO DE RESIDENCIA` == "LAGOA REAL" ~ "Lagoa Real",
    `MUNICIPIO DE RESIDENCIA` == "LAJE" ~ "Laje",
    `MUNICIPIO DE RESIDENCIA` == "LAJEDAO" ~ "Lajedão",
    `MUNICIPIO DE RESIDENCIA` == "LAJEDINHO" ~ "Lajedinho",
    `MUNICIPIO DE RESIDENCIA` == "LAJEDO DO TABOCAL" ~ "Lajedo do Tabocal",
    `MUNICIPIO DE RESIDENCIA` == "LAMARAO" ~ "Lamarão",
    `MUNICIPIO DE RESIDENCIA` == "LAPAO" ~ "Lapão",
    `MUNICIPIO DE RESIDENCIA` == "LAURO DE FREITAS" ~ "Lauro de Freitas",
    `MUNICIPIO DE RESIDENCIA` == "LENCOIS" ~ "Lençóis",
    `MUNICIPIO DE RESIDENCIA` == "LICINIO DE ALMEIDA" ~ "Licínio de Almeida",
    `MUNICIPIO DE RESIDENCIA` == "LIVRAMENTO DE NOSSA SENHORA" ~ "Livramento de Nossa Senhora",
    `MUNICIPIO DE RESIDENCIA` == "LPI- ALAGOINHAS" ~ "Alagoinhas",
    `MUNICIPIO DE RESIDENCIA` == "LPI- AMARGOSA" ~ "Amargosa",
    `MUNICIPIO DE RESIDENCIA` == "LPI- BIRITINGA" ~ "Biritinga",
    `MUNICIPIO DE RESIDENCIA` == "LPI- BOM JESUS DA LAPA" ~ "Bom Jesus da Lapa",
    `MUNICIPIO DE RESIDENCIA` == "LPI- BONITO" ~ "Bonito",
    `MUNICIPIO DE RESIDENCIA` == "LPI- CABACEIRAS DO PARAGUACU" ~ "Cabaceiras do Paraguaçu",
    `MUNICIPIO DE RESIDENCIA` == "LPI- CACULE" ~ "Caculé",
    `MUNICIPIO DE RESIDENCIA` == "LPI- CAETANOS" ~ "Caetanos",
    `MUNICIPIO DE RESIDENCIA` == "LPI- CAMAMU" ~ "Camamu",
    `MUNICIPIO DE RESIDENCIA` == "LPI- CAMPO FORMOSO" ~ "Campo Formoso",
    `MUNICIPIO DE RESIDENCIA` == "LPI- CANUDOS" ~ "Canudos",
    `MUNICIPIO DE RESIDENCIA` == "LPI- CATU" ~ "Catu",
    `MUNICIPIO DE RESIDENCIA` == "LPI- CORIBE" ~ "Coribe",
    `MUNICIPIO DE RESIDENCIA` == "LPI- CRUZ DAS ALMAS" ~ "Cruz das Almas",
    `MUNICIPIO DE RESIDENCIA` == "LPI- FEIRA DE SANTANA" ~ "Feira de Santana",
    `MUNICIPIO DE RESIDENCIA` == "LPI- INHAMBUPE" ~ "Inhambupe",
    `MUNICIPIO DE RESIDENCIA` == "LPI- LAJE" ~ "Laje",
    `MUNICIPIO DE RESIDENCIA` == "LPI- LAPAO" ~ "Lapão",
    `MUNICIPIO DE RESIDENCIA` == "LPI- MIGUEL CALMON" ~ "Miguel Calmon",
    `MUNICIPIO DE RESIDENCIA` == "LPI- MORRO DO CHAPEU" ~ "Morro do Chapéu",
    `MUNICIPIO DE RESIDENCIA` == "LPI- MULUNGU DO MORRO" ~ "Mulungu do Morro",
    `MUNICIPIO DE RESIDENCIA` == "LPI- NOVA IBIA" ~ "Nova Ibiá",
    `MUNICIPIO DE RESIDENCIA` == "LPI- PILAO ARCADO" ~ "Pilão Arcado",
    `MUNICIPIO DE RESIDENCIA` == "LPI- SANTA CRUZ CABRALIA" ~ "Santa Cruz Cabrália",
    `MUNICIPIO DE RESIDENCIA` == "LPI- SANTA INES" ~ "Santa Inês",
    `MUNICIPIO DE RESIDENCIA` == "LPI- SAUBARA" ~ "Saubara",
    `MUNICIPIO DE RESIDENCIA` == "LPI- SAUDE" ~ "Saúde",
    `MUNICIPIO DE RESIDENCIA` == "LPI- SEABRA" ~ "Seabra",
    `MUNICIPIO DE RESIDENCIA` == "LPI- SERRA DO RAMALHO" ~ "Serra do Ramalho",
    `MUNICIPIO DE RESIDENCIA` == "LPI- UBAIRA" ~ "Ubaíra",
    `MUNICIPIO DE RESIDENCIA` == "LUIS EDUARDO MAGALHAES" ~ "Luís Eduardo Magalhães",
    `MUNICIPIO DE RESIDENCIA` == "MACAJUBA" ~ "Macajuba",
    `MUNICIPIO DE RESIDENCIA` == "MACARANI" ~ "Macarani",
    `MUNICIPIO DE RESIDENCIA` == "MACAUBAS" ~ "Macaúbas",
    `MUNICIPIO DE RESIDENCIA` == "MACURURE" ~ "Macururé",
    `MUNICIPIO DE RESIDENCIA` == "MADRE DE DEUS" ~ "Madre de Deus",
    `MUNICIPIO DE RESIDENCIA` == "MAETINGA" ~ "Maetinga",
    `MUNICIPIO DE RESIDENCIA` == "MAIQUINIQUE" ~ "Maiquinique",
    `MUNICIPIO DE RESIDENCIA` == "MAIRI" ~ "Mairi",
    `MUNICIPIO DE RESIDENCIA` == "MALHADA" ~ "Malhada",
    `MUNICIPIO DE RESIDENCIA` == "MALHADA DE PEDRAS" ~ "Malhada de Pedras",
    `MUNICIPIO DE RESIDENCIA` == "MANOEL VITORINO" ~ "Manoel Vitorino",
    `MUNICIPIO DE RESIDENCIA` == "MANSIDAO" ~ "Mansidão",
    `MUNICIPIO DE RESIDENCIA` == "MARACAS" ~ "Maracás",
    `MUNICIPIO DE RESIDENCIA` == "MARAGOGIPE" ~ "Maragogipe",
    `MUNICIPIO DE RESIDENCIA` == "MARAU" ~ "Maraú",
    `MUNICIPIO DE RESIDENCIA` == "MARCIONILIO SOUZA" ~ "Marcionílio Souza",
    `MUNICIPIO DE RESIDENCIA` == "MASCOTE" ~ "Mascote",
    `MUNICIPIO DE RESIDENCIA` == "MATA DE SAO JOAO" ~ "Mata de São João",
    `MUNICIPIO DE RESIDENCIA` == "MATINA" ~ "Matina",
    `MUNICIPIO DE RESIDENCIA` == "MEDEIROS NETO" ~ "Medeiros Neto",
    `MUNICIPIO DE RESIDENCIA` == "MIGUEL CALMON" ~ "Miguel Calmon",
    `MUNICIPIO DE RESIDENCIA` == "MILAGRES" ~ "Milagres",
    `MUNICIPIO DE RESIDENCIA` == "MIRANGABA" ~ "Mirangaba",
    `MUNICIPIO DE RESIDENCIA` == "MIRANTE" ~ "Mirante",
    `MUNICIPIO DE RESIDENCIA` == "MONTE SANTO" ~ "Monte Santo",
    `MUNICIPIO DE RESIDENCIA` == "MORPARA" ~ "Morpará",
    `MUNICIPIO DE RESIDENCIA` == "MORRO DO CHAPEU" ~ "Morro do Chapéu",
    `MUNICIPIO DE RESIDENCIA` == "MORTUGABA" ~ "Mortugaba",
    `MUNICIPIO DE RESIDENCIA` == "MUCUGE" ~ "Mucugê",
    `MUNICIPIO DE RESIDENCIA` == "MUCURI" ~ "Mucuri",
    `MUNICIPIO DE RESIDENCIA` == "MULUNGU DO MORRO" ~ "Mulungu do Morro",
    `MUNICIPIO DE RESIDENCIA` == "MUNDO NOVO" ~ "Mundo Novo",
    `MUNICIPIO DE RESIDENCIA` == "MUNIZ FERREIRA" ~ "Muniz Ferreira",
    `MUNICIPIO DE RESIDENCIA` == "MUQUEM DE SAO FRANCISCO" ~ "Muquém do São Francisco",
    `MUNICIPIO DE RESIDENCIA` == "MURITIBA" ~ "Muritiba",
    `MUNICIPIO DE RESIDENCIA` == "MUTUIPE" ~ "Mutuípe",
    `MUNICIPIO DE RESIDENCIA` == "NAZARE" ~ "Nazaré",
    `MUNICIPIO DE RESIDENCIA` == "NILO PECANHA" ~ "Nilo Peçanha",
    `MUNICIPIO DE RESIDENCIA` == "NORDESTINA" ~ "Nordestina",
    `MUNICIPIO DE RESIDENCIA` == "NOVA CANAA" ~ "Nova Canaã",
    `MUNICIPIO DE RESIDENCIA` == "NOVA FATIMA" ~ "Nova Fátima",
    `MUNICIPIO DE RESIDENCIA` == "NOVA IBIA" ~ "Nova Ibiá",
    `MUNICIPIO DE RESIDENCIA` == "NOVA ITARANA" ~ "Nova Itarana",
    `MUNICIPIO DE RESIDENCIA` == "NOVA REDENCAO" ~ "Nova Redenção",
    `MUNICIPIO DE RESIDENCIA` == "NOVA SOURE" ~ "Nova Soure",
    `MUNICIPIO DE RESIDENCIA` == "NOVA VICOSA" ~ "Nova Viçosa",
    `MUNICIPIO DE RESIDENCIA` == "NOVO HORIZONTE" ~ "Novo Horizonte",
    `MUNICIPIO DE RESIDENCIA` == "NOVO TRIUNFO" ~ "Novo Triunfo",
    `MUNICIPIO DE RESIDENCIA` == "OLINDINA" ~ "Olindina",
    `MUNICIPIO DE RESIDENCIA` == "OLIVEIRA DOS BREJINHOS" ~ "Oliveira dos Brejinhos",
    `MUNICIPIO DE RESIDENCIA` == "OURICANGAS" ~ "Ouriçangas",
    `MUNICIPIO DE RESIDENCIA` == "OUROLANDIA" ~ "Ourolândia",
    `MUNICIPIO DE RESIDENCIA` == "PALMAS DE MONTE ALTO" ~ "Palmas de Monte Alto",
    `MUNICIPIO DE RESIDENCIA` == "PALMEIRAS" ~ "Palmeiras",
    `MUNICIPIO DE RESIDENCIA` == "PARAMIRIM" ~ "Paramirim",
    `MUNICIPIO DE RESIDENCIA` == "PARATINGA" ~ "Paratinga",
    `MUNICIPIO DE RESIDENCIA` == "PARIPIRANGA" ~ "Paripiranga",
    `MUNICIPIO DE RESIDENCIA` == "PAU BRASIL" ~ "Pau-Brasil",
    `MUNICIPIO DE RESIDENCIA` == "PAULO AFONSO" ~ "Paulo Afonso",
    `MUNICIPIO DE RESIDENCIA` == "PE DE SERRA" ~ "Pé de Serra",
    `MUNICIPIO DE RESIDENCIA` == "PEDRAO" ~ "Pedrão",
    `MUNICIPIO DE RESIDENCIA` == "PEDRO ALEXANDRE" ~ "Pedro Alexandre",
    `MUNICIPIO DE RESIDENCIA` == "PIATA" ~ "Piatã",
    `MUNICIPIO DE RESIDENCIA` == "PILAO ARCADO" ~ "Pilão Arcado",
    `MUNICIPIO DE RESIDENCIA` == "PINDAI" ~ "Pindaí",
    `MUNICIPIO DE RESIDENCIA` == "PINDOBACU" ~ "Pindobaçu",
    `MUNICIPIO DE RESIDENCIA` == "PINTADAS" ~ "Pintadas",
    `MUNICIPIO DE RESIDENCIA` == "PIRAI DO NORTE" ~ "Piraí do Norte",
    `MUNICIPIO DE RESIDENCIA` == "PIRIPA" ~ "Piripá",
    `MUNICIPIO DE RESIDENCIA` == "PIRITIBA" ~ "Piritiba",
    `MUNICIPIO DE RESIDENCIA` == "PLANALTINO" ~ "Planaltino",
    `MUNICIPIO DE RESIDENCIA` == "PLANALTO" ~ "Planalto",
    `MUNICIPIO DE RESIDENCIA` == "POC??ES" ~ "Poções",
    `MUNICIPIO DE RESIDENCIA` == "POCOES" ~ "Poções",
    `MUNICIPIO DE RESIDENCIA` == "POJUCA" ~ "Pojuca",
    `MUNICIPIO DE RESIDENCIA` == "PONTO NOVO" ~ "Ponto Novo",
    `MUNICIPIO DE RESIDENCIA` == "PORTO SEGURO" ~ "Porto Seguro",
    `MUNICIPIO DE RESIDENCIA` == "POTIRAGUA" ~ "Potiraguá",
    `MUNICIPIO DE RESIDENCIA` == "PRADO" ~ "Prado",
    `MUNICIPIO DE RESIDENCIA` == "PRESIDENTE DUTRA" ~ "Presidente Dutra",
    `MUNICIPIO DE RESIDENCIA` == "PRESIDENTE JANIO QUADROS" ~ "Presidente Jânio Quadros",
    `MUNICIPIO DE RESIDENCIA` == "PRESIDENTE TANCREDO NEVES" ~ "Presidente Tancredo Neves",
    `MUNICIPIO DE RESIDENCIA` == "QUEIMADAS" ~ "Queimadas",
    `MUNICIPIO DE RESIDENCIA` == "QUIJINGUE" ~ "Quijingue",
    `MUNICIPIO DE RESIDENCIA` == "QUIXABEIRA" ~ "Quixabeira",
    `MUNICIPIO DE RESIDENCIA` == "RAFAEL JAMBEIRO" ~ "Rafael Jambeiro",
    `MUNICIPIO DE RESIDENCIA` == "REMANSO" ~ "Remanso",
    `MUNICIPIO DE RESIDENCIA` == "RETIROLANDIA" ~ "Retirolândia",
    `MUNICIPIO DE RESIDENCIA` == "RIACHAO DAS NEVES" ~ "Riachão das Neves",
    `MUNICIPIO DE RESIDENCIA` == "RIACHAO DO JACUIPE" ~ "Riachão do Jacuípe",
    `MUNICIPIO DE RESIDENCIA` == "RIACHO DE SANTANA" ~ "Riacho de Santana",
    `MUNICIPIO DE RESIDENCIA` == "RIBEIRA DO AMPARO" ~ "Ribeira do Amparo",
    `MUNICIPIO DE RESIDENCIA` == "RIBEIRA DO POMBAL" ~ "Ribeira do Pombal",
    `MUNICIPIO DE RESIDENCIA` == "RIBEIRAO DO LARGO" ~ "Ribeirão do Largo",
    `MUNICIPIO DE RESIDENCIA` == "RIO DE CONTAS" ~ "Rio de Contas",
    `MUNICIPIO DE RESIDENCIA` == "RIO DO ANTONIO" ~ "Rio do Antônio",
    `MUNICIPIO DE RESIDENCIA` == "RIO DO PIRES" ~ "Rio do Pires",
    `MUNICIPIO DE RESIDENCIA` == "RIO REAL" ~ "Rio Real",
    `MUNICIPIO DE RESIDENCIA` == "RODA VELHA" ~ "São Desidério",
    `MUNICIPIO DE RESIDENCIA` == "RODELAS" ~ "Rodelas",
    `MUNICIPIO DE RESIDENCIA` == "RUY BARBOSA" ~ "Ruy Barbosa",
    `MUNICIPIO DE RESIDENCIA` == "SAIVADOR" ~ "Salvador",
    `MUNICIPIO DE RESIDENCIA` == "SALINAS DA MARGARIDA" ~ "Salinas da Margarida",
    `MUNICIPIO DE RESIDENCIA` == "SALVADOR" ~ "Salvador",
    `MUNICIPIO DE RESIDENCIA` == "SANTA BARBARA" ~ "Santa Bárbara",
    `MUNICIPIO DE RESIDENCIA` == "SANTA BRIGIDA" ~ "Santa Brígida",
    `MUNICIPIO DE RESIDENCIA` == "SANTA CRUZ CABRALIA" ~ "Santa Cruz Cabrália",
    `MUNICIPIO DE RESIDENCIA` == "SANTA CRUZ DA VITORIA" ~ "Santa Cruz da Vitória",
    `MUNICIPIO DE RESIDENCIA` == "SANTA INES" ~ "Santa Inês",
    `MUNICIPIO DE RESIDENCIA` == "SANTA LUZIA" ~ "Santa Luzia",
    `MUNICIPIO DE RESIDENCIA` == "SANTA MARIA DA VITORIA" ~ "Santa Maria da Vitória",
    `MUNICIPIO DE RESIDENCIA` == "SANTA RITA DE CASSIA" ~ "Santa Rita de Cássia",
    `MUNICIPIO DE RESIDENCIA` == "SANTA TERESINHA" ~ "Santa Terezinha",
    `MUNICIPIO DE RESIDENCIA` == "SANTALUZ" ~ "Santaluz",
    `MUNICIPIO DE RESIDENCIA` == "SANTANA" ~ "Santana",
    `MUNICIPIO DE RESIDENCIA` == "SANTANOPOLIS" ~ "Santanópolis",
    `MUNICIPIO DE RESIDENCIA` == "SANTO AMARO" ~ "Santo Amaro",
    `MUNICIPIO DE RESIDENCIA` == "SANTO ANTONIO DE JESUS" ~ "Santo Antônio de Jesus",
    `MUNICIPIO DE RESIDENCIA` == "SANTO ESTEVAO" ~ "Santo Estêvão",
    `MUNICIPIO DE RESIDENCIA` == "SAO DESIDERIO" ~ "São Desidério",
    `MUNICIPIO DE RESIDENCIA` == "SAO DOMINGOS" ~ "São Domingos",
    `MUNICIPIO DE RESIDENCIA` == "SAO FELIPE" ~ "São Felipe",
    `MUNICIPIO DE RESIDENCIA` == "SAO FELIX" ~ "São Félix",
    `MUNICIPIO DE RESIDENCIA` == "SAO FELIX DO CORIBE" ~ "São Félix do Coribe",
    `MUNICIPIO DE RESIDENCIA` == "SAO FRANCISCO DO CONDE" ~ "São Francisco do Conde",
    `MUNICIPIO DE RESIDENCIA` == "SAO GABRIEL" ~ "São Gabriel",
    `MUNICIPIO DE RESIDENCIA` == "SAO GONCALO DOS CAMPOS" ~ "São Gonçalo dos Campos",
    `MUNICIPIO DE RESIDENCIA` == "SAO JOSE DA VITORIA" ~ "São José da Vitória",
    `MUNICIPIO DE RESIDENCIA` == "SAO JOSE DO JACUIPE" ~ "São José do Jacuípe",
    `MUNICIPIO DE RESIDENCIA` == "SAO MIGUEL DAS MATAS" ~ "São Miguel das Matas",
    `MUNICIPIO DE RESIDENCIA` == "SAO SEBASTIAO DO PASSE" ~ "São Sebastião do Passé",
    `MUNICIPIO DE RESIDENCIA` == "SAPEACU" ~ "Sapeaçu",
    `MUNICIPIO DE RESIDENCIA` == "SATIRO DIAS" ~ "Sátiro Dias",
    `MUNICIPIO DE RESIDENCIA` == "SAUBARA" ~ "Saubara",
    `MUNICIPIO DE RESIDENCIA` == "SAUDE" ~ "Saúde",
    `MUNICIPIO DE RESIDENCIA` == "SEABRA" ~ "Seabra",
    `MUNICIPIO DE RESIDENCIA` == "SEBASTIAO LARANJEIRAS" ~ "Sebastião Laranjeiras",
    `MUNICIPIO DE RESIDENCIA` == "SENHOR DO BONFIM" ~ "Senhor do Bonfim",
    `MUNICIPIO DE RESIDENCIA` == "SENTO SE" ~ "Sento Sé",
    `MUNICIPIO DE RESIDENCIA` == "SERRA DO RAMALHO" ~ "Serra do Ramalho",
    `MUNICIPIO DE RESIDENCIA` == "SERRA DOURADA" ~ "Serra Dourada",
    `MUNICIPIO DE RESIDENCIA` == "SERRA GRANDE" ~ "Valença",
    `MUNICIPIO DE RESIDENCIA` == "SERRA PRETA" ~ "Serra Preta",
    `MUNICIPIO DE RESIDENCIA` == "SERRINHA" ~ "Serrinha",
    `MUNICIPIO DE RESIDENCIA` == "SERROLANDIA" ~ "Serrolândia",
    `MUNICIPIO DE RESIDENCIA` == "SIMOES FILHO" ~ "Simões Filho",
    `MUNICIPIO DE RESIDENCIA` == "SITIO DO MATO" ~ "Sítio do Mato",
    `MUNICIPIO DE RESIDENCIA` == "SITIO DO QUINTO" ~ "Sítio do Quinto",
    `MUNICIPIO DE RESIDENCIA` == "SOBRADINHO" ~ "Sobradinho",
    `MUNICIPIO DE RESIDENCIA` == "SOUTO SOARES" ~ "Souto Soares",
    `MUNICIPIO DE RESIDENCIA` == "TABOCAS DO BREJO VELHO" ~ "Tabocas do Brejo Velho",
    `MUNICIPIO DE RESIDENCIA` == "TANHACU" ~ "Tanhaçu",
    `MUNICIPIO DE RESIDENCIA` == "TANQUE NOVO" ~ "Tanque Novo",
    `MUNICIPIO DE RESIDENCIA` == "TANQUINHO" ~ "Tanquinho",
    `MUNICIPIO DE RESIDENCIA` == "TAPEROA" ~ "Taperoá",
    `MUNICIPIO DE RESIDENCIA` == "TAPIRAMUTA" ~ "Tapiramutá",
    `MUNICIPIO DE RESIDENCIA` == "TEIXEIRA DE FREITAS" ~ "Teixeira de Freitas",
    `MUNICIPIO DE RESIDENCIA` == "TEODORO SAMPAIO" ~ "Teodoro Sampaio",
    `MUNICIPIO DE RESIDENCIA` == "TEOFILANDIA" ~ "Teofilândia",
    `MUNICIPIO DE RESIDENCIA` == "TEOLANDIA" ~ "Teolândia",
    `MUNICIPIO DE RESIDENCIA` == "TERRA NOVA" ~ "Terra Nova",
    `MUNICIPIO DE RESIDENCIA` == "TREMEDAL" ~ "Tremedal",
    `MUNICIPIO DE RESIDENCIA` == "TUCANO" ~ "Tucano",
    `MUNICIPIO DE RESIDENCIA` == "UAUA" ~ "Uauá",
    `MUNICIPIO DE RESIDENCIA` == "UBAIRA" ~ "Ubaíra",
    `MUNICIPIO DE RESIDENCIA` == "UBAITABA" ~ "Ubaitaba",
    `MUNICIPIO DE RESIDENCIA` == "UBATA" ~ "Ubatã",
    `MUNICIPIO DE RESIDENCIA` == "UIBAI" ~ "Uibaí",
    `MUNICIPIO DE RESIDENCIA` == "UMBURANAS" ~ "Umburanas",
    `MUNICIPIO DE RESIDENCIA` == "UNA" ~ "Una",
    `MUNICIPIO DE RESIDENCIA` == "URANDI" ~ "Urandi",
    `MUNICIPIO DE RESIDENCIA` == "URUCUCA" ~ "Uruçuca",
    `MUNICIPIO DE RESIDENCIA` == "UTINGA" ~ "Utinga",
    `MUNICIPIO DE RESIDENCIA` == "VALENCA" ~ "Valença",
    `MUNICIPIO DE RESIDENCIA` == "VALENTE" ~ "Valente",
    `MUNICIPIO DE RESIDENCIA` == "VARZEA DA ROCA" ~ "Várzea da Roça",
    `MUNICIPIO DE RESIDENCIA` == "VARZEA DO POCO" ~ "Várzea do Poço",
    `MUNICIPIO DE RESIDENCIA` == "VARZEA NOVA" ~ "Várzea Nova",
    `MUNICIPIO DE RESIDENCIA` == "VARZEDO" ~ "Varzedo",
    `MUNICIPIO DE RESIDENCIA` == "VERA CRUZ" ~ "Vera Cruz",
    `MUNICIPIO DE RESIDENCIA` == "VEREDA" ~ "Vereda",
    `MUNICIPIO DE RESIDENCIA` == "VITORIA DA CONQUISTA" ~ "Vitória da Conquista",
    `MUNICIPIO DE RESIDENCIA` == "WAGNER" ~ "Wagner",
    `MUNICIPIO DE RESIDENCIA` == "WANDERLEY" ~ "Wanderley",
    `MUNICIPIO DE RESIDENCIA` == "WENCESLAU GUIMARAES" ~ "Wenceslau Guimarães",
    `MUNICIPIO DE RESIDENCIA` == "XIQUE-XIQUE" ~ "Xique-Xique"),
    estado_residencia = case_when(
      `ESTADO DE RESIDENCIA` =="ACRE" ~ "Acre",
        `ESTADO DE RESIDENCIA` =="AL" ~ "Alagoas",
        `ESTADO DE RESIDENCIA` =="ALAGOAS" ~ "Alagoas",
        `ESTADO DE RESIDENCIA` =="AM" ~ "Amazonas",
        `ESTADO DE RESIDENCIA` =="AMAPA" ~ "Amapá",
        `ESTADO DE RESIDENCIA` =="AMAZONAS" ~ "Amazonas",
        `ESTADO DE RESIDENCIA` =="AMAZONAS/MANAUS" ~ "Amazonas",
        `ESTADO DE RESIDENCIA` =="BAHIA" ~ "Bahia",
        `ESTADO DE RESIDENCIA` =="BRASILIA" ~ "Distrito Federal",
        `ESTADO DE RESIDENCIA` =="CE" ~ "Ceará",
        `ESTADO DE RESIDENCIA` =="CEARA" ~ "Ceará",
        `ESTADO DE RESIDENCIA` =="CEARA/JAGUARIBARA" ~ "Ceará",
        `ESTADO DE RESIDENCIA` =="CEARA/JUAZEIRO DO NORTE" ~ "Ceará",
        `ESTADO DE RESIDENCIA` =="CURITIBA" ~ "Paraná",
        `ESTADO DE RESIDENCIA` =="DISTRITO FEDERAL" ~ "Distrito Federal",
        `ESTADO DE RESIDENCIA` =="ES" ~ "Espírito Santo",
        `ESTADO DE RESIDENCIA` =="ESPIRITO SANTO" ~ "Espírito Santo",
        `ESTADO DE RESIDENCIA` =="FORTALEZA" ~ "Ceará",
        `ESTADO DE RESIDENCIA` =="GO" ~ "Goiás",
        `ESTADO DE RESIDENCIA` =="GO/ANAPOLIS" ~ "Goiás",
        `ESTADO DE RESIDENCIA` =="GOIANIA" ~ "Goiás",
        `ESTADO DE RESIDENCIA` =="GOIAS" ~ "Goiás",
        `ESTADO DE RESIDENCIA` =="MA" ~ "Maranhão",
        `ESTADO DE RESIDENCIA` =="MANAUS" ~ "Amazonas",
        `ESTADO DE RESIDENCIA` =="MARANHAO" ~ "Maranhão",
        `ESTADO DE RESIDENCIA` =="MATO GROSSO" ~ "Mato Grosso",
        `ESTADO DE RESIDENCIA` =="MATO GROSSO DO SUL" ~ "Mato Grosso do Sul",
        `ESTADO DE RESIDENCIA` =="MG" ~ "Minas Gerais",
        `ESTADO DE RESIDENCIA` =="MINAS GERAIS" ~ "Minas Gerais",
        `ESTADO DE RESIDENCIA` =="MS" ~ "Mato Grosso do Sul",
        `ESTADO DE RESIDENCIA` =="MT" ~ "Mato Grosso",
        `ESTADO DE RESIDENCIA` =="PA" ~ "Pará",
        `ESTADO DE RESIDENCIA` =="PARA" ~ "Pará",
        `ESTADO DE RESIDENCIA` =="PARAIBA" ~ "Paraíba",
        `ESTADO DE RESIDENCIA` =="PARANA" ~ "Paraná",
        `ESTADO DE RESIDENCIA` =="PB" ~ "Paraíba",
        `ESTADO DE RESIDENCIA` =="PE" ~ "Pernambuco",
        `ESTADO DE RESIDENCIA` =="PERNAMBUCO" ~ "Pernambuco",
        `ESTADO DE RESIDENCIA` =="PI" ~ "Piauí",
        `ESTADO DE RESIDENCIA` =="PIAUI" ~ "Piauí",
        `ESTADO DE RESIDENCIA` =="PR" ~ "Paraná",
        `ESTADO DE RESIDENCIA` =="RECIFE" ~ "Pernambuco",
        `ESTADO DE RESIDENCIA` =="RIO DE JANEIRO" ~ "Rio de Janeiro",
        `ESTADO DE RESIDENCIA` =="RIO GRANDE DO NORTE" ~ "Rio Grande do Norte",
        `ESTADO DE RESIDENCIA` =="RIO GRANDE DO SUL" ~ "Rio Grande do Sul",
        `ESTADO DE RESIDENCIA` =="RJ" ~ "Rio de Janeiro",
        `ESTADO DE RESIDENCIA` =="RN" ~ "Rio Grande do Norte",
        `ESTADO DE RESIDENCIA` =="RO" ~ "Rondônia",
        `ESTADO DE RESIDENCIA` =="RONDONIA" ~ "Rondônia",
        `ESTADO DE RESIDENCIA` =="RORAIMA" ~ "Roraima",
        `ESTADO DE RESIDENCIA` =="RS" ~ "Rio Grande do Sul",
        `ESTADO DE RESIDENCIA` =="S?O PAULO" ~ "São Paulo",
        `ESTADO DE RESIDENCIA` =="SANTA CATARINA" ~ "Santa Catarina",
        `ESTADO DE RESIDENCIA` =="SAO PAULO" ~ "São Paulo",
        `ESTADO DE RESIDENCIA` =="SC" ~ "Santa Catarina",
        `ESTADO DE RESIDENCIA` =="SE" ~ "Sergipe",
        `ESTADO DE RESIDENCIA` =="SERGIPE" ~ "Sergipe",
        `ESTADO DE RESIDENCIA` =="SP" ~ "São Paulo",
        `ESTADO DE RESIDENCIA` =="TO" ~ "Tocantins",
        `ESTADO DE RESIDENCIA` =="TOCANTINS" ~ "Tocantins"
    )
    
)

# Unindo com dataset dos códigos 
Sesab_v2 <- left_join(Sesab_v2, codigos_mun, by = c("municipio_residencia" = "Nome_Municipio",
                                                    "estado_residencia" = "Nome_UF"),all.x = TRUE)



# Unindo com dataset dos NRS
Sesab_v2 <- left_join(Sesab_v2, nrs_pop, by = c("Codigo_mun" = "CD_GEOCMU"),all.x = TRUE)

#  removendo coluna de municípios que não era utilizada
Sesab_v2$NM_MUNICIP2 <- NULL

# ajustando datas 
Sesab_v2$`DATA DA NOTIFICACAO` <- dmy(Sesab_v2$`DATA DA NOTIFICACAO`)
Sesab_v2$`DATA DO INICIO DOS SINTOMAS` <- dmy(Sesab_v2$`DATA DO INICIO DOS SINTOMAS`)
Sesab_v2$`DATA DA COLETA DO TESTE` <- dmy(Sesab_v2$`DATA DA COLETA DO TESTE`)


# Salvando
write.csv2(Sesab_v2,"Dados_gerais_SESAB_20jul.csv", row.names = F)



